print("wwwwwww")
print("w     w")
print("w     w")
print("w     w")
print("w     w")
print("wwwwwww")
print("       ")
print("       ")
print("iiiiiii")
print("     ii")
print("    ii ")
print("   ii  ")
print(" ii    ")
print("ii     ")
print("       ")
print("       ")
print("nnnnnnn")
print("n      ")
print("n      ")
print("nnnnnnn")
print("n     n")
print("n     n")
print("nnnnnnn")